### ISSUE TITLE
Dude plz stop changing the DAH attack names everytime time

### ISSUE THREAD

**Issue by SendHelPlz** [hsdn/tera-guide#28]

**Comment by SendHelPlz** [comment]
Like : ''Just put left foot, right foot and etc, no LEFT FOOT OUT IN LEFT STAY OUT GET IN''

**Comment by shindmitry** [comment]
We did not change the message about the main Pizza mechanics ("Left Foot" or "Right Foot" - this text has always been in all versions), but only added a text part about where to go on the waves/donuts, because were received requests from players. The current notification messages is final and will not be changed. However, we do allow minor translation corrections (for all guides).

**Comment by SendHelPlz** [comment]
> We did not change the message about the main Pizza mechanics ("Left Foot" or "Right Foot" - this text has always been in all versions), but only added a text part about where to go on the waves/donuts, because were received requests from players. The current notification messages is final and will not be changed. However, we do allow minor translation corrections (for all guides).

it’s more difficult to do the mechanics, no one will be able to read it all and do it at the same time, I think it’s fairer to just report the attack, the person needs to learn what to do. anyway. Thanks for the attention anyway
