### ISSUE TITLE
Lags/Slow

### ISSUE THREAD

**Issue by fisherman1717** [hsdn/tera-guide#35]
seems like many people complaining that the latest guide is slowing down or clashing with code from skill prediction mods?

**Comment by shindmitry** [comment]
We are not aware of such problems.

**Comment by Multarix** [comment]
I have also not encountered such a problem.

**Comment by shindmitry** [comment]
There is an opinion that now there are basic problems with the Toolbox or the skrill-prediction module, due to which lags and freezes are observed. The many of players blame the guide module for these problems, but there is no real confirmation of this information.

**Comment by fisherman1717** [comment]
the main moderator of toolbox is saying that your guide is badly coded and causing the lags and freezes.
You can discuss with him at his discord: Powah#2354

**Comment by shindmitry** [comment]
He only pointed out problems with setTimeout() that had been resolved.

**Comment by shindmitry** [comment]
I personally discuss with him on the subject. He didn't identify any things in the script that could cause such problems.

**Comment by Multarix** [comment]
I just checked discord and he has not talked about it in the last 24 hours, I think this is old news.

**Comment by KYGAS** [comment]
If you so need, I will gladly make a simple guide for you on how to delete a repository, your guide is legit raping old PCs performance wise, stop adding stuff and optimize and fix what you have. Thanks

**Comment by SaltyMonkey** [comment]
Well, i want to point 5 thingies.
1) We are never "discussed" something. You randomly appeared and i pointed first easiest issue what i checked after XXX reports.
You answered "its fixed" so i said "ok" and never investigated smth after dat.
2) `I just checked discord and he has not talked about it in the last 24 hours, I think this is old news.` sounds kinda as good joke tho...
3) `There is an opinion that now there are basic problems with the Toolbox or the skrill-prediction module` no, there isnt any problem related to your issue. As i pointed in our "discussion" - you should learn how nodejs event loop works.
4) No need to refer at my opinion completely when you reporting bugs to developers (its for @fisherman1717 ). Developers need some proofs.
5) A lot users have old versions installed with disabled autoupdates (maybe some personal changes? idk). So issue apparently still here.

**Comment by shindmitry** [comment]
@SaltyMonkey, 
In any case, at time we do not believe that there are any problems with our code (from your or other users). The timers problems were present in all guides, starting with the first version from Kasea, but there were no previous reports about them. But this problem is fixed in our version of the script and fork by @Multarix. We are not aware of any other problems.

About Toolbox and SP - we were informed by people that the problems with freezes and lags were solved by a clean installation of the latest version of the Toolbox.

**Comment by fisherman1717** [comment]
I turned off this tera-guide, and the slows/lags are gone, spell chain quicker and more smoothly now.
Hopefully you fix your code , as it's not good when the guide affects the gameplay negatively

**Comment by shindmitry** [comment]
Try to install latest version of tera-guide, many problems is fixed.

**Comment by shindmitry** [comment]
Also you should understand that the use of any guide leads to an additional load on the CPU and reduces the FPS, because additional objects are spawned and playing voice. You can disable this features (by **guide spawnObject** and **guide voice** commands or via GUI) and leaving only text messages in the chat.
