### ISSUE TITLE
csn/h in out bug (telling wrong spot)

### ISSUE THREAD

**Issue by akamech4n** [hsdn/tera-guide#4]
hi, can u for some chance can check and try fix csn/h, some times for some reason guide telling wrong messages
Ex : Telling me to get out when i need to get inside (this is after NA 06/09/2020 patch)

**Comment by shindmitry** [comment]
This is NA TERA server-side problem. A server sends the QuestBalloon packet later than necessary, because of which there is a conflict in the order of setting variables.

The wrong order is shown on the illustration:
![](http://dev.hsdn.org/git/oRGWkRXM.png)
You need to wait for the fix from the TERA Team. I can’t fix it.

https://github.com/michengs/Dungeon-guide/issues/1
https://github.com/michengs/tera-guide/issues/1

**Comment by shindmitry** [comment]
Presumably fixed in commit https://github.com/hsdn/tera-guide/commit/aea5fda59415dd305d647ae71532b0a16bf23a14
Please update and test.

**Comment by salman90299** [comment]
![image](https://user-images.githubusercontent.com/28118014/84346983-0a1a8b80-abba-11ea-9029-e0d83a1fae17.png)

Getting this now after the recent commit

**Comment by Silas-ux** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/28118014/84346983-0a1a8b80-abba-11ea-9029-e0d83a1fae17.png)
> 
> Getting this now after the recent commit
> 
> EU btw

in NA too, first happen this ^

after happen this > ![image](https://user-images.githubusercontent.com/66766432/84347531-37027a80-ab89-11ea-8a77-a84ab694ab9e.png) translation: "the mod tera-guide don't support automatic updates"

**Comment by shindmitry** [comment]
This problem on github side. Please wait and try arain.

**Comment by shindmitry** [comment]
Github has updated manifest.json in cache. Please try to get updates again.

**Comment by Silas-ux** [comment]
and this? 
![image](https://user-images.githubusercontent.com/66766432/84355078-6371c300-ab98-11ea-8b1a-75fbb92d18fd.png)
